name: Test Build Push

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Test
      run: dotnet test tests/Cake.Gerrit.Tests/Cake.Gerrit.Tests.csproj
    - name: Build
      run: |
        find . -name "*.nupkg" -type f -delete
        dotnet build -c Release
    - name: Push
      run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NugetCakeKey}} --source https://api.nuget.org/v3/index.json --no-symbols true
